# Generated by Django 3.2.13 on 2022-06-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=30)),
                ('disponible', models.BooleanField()),
                ('fechaIncorporacion', models.DateField()),
                ('correoProveedor', models.EmailField(max_length=254)),
            ],
        ),
    ]
